apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: album-manager
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: album-manager
    spec:
      containers:
      - name: album-manager
        image: peer1989/neo_test_album:v28
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 5001
        volumeMounts:
          - mountPath: /data/app-data
            name: album-manager
      volumes: 
         - name: album-manager
           persistentVolumeClaim:
             claimName: pv-claim