global:
  scrape_interval: 5s
  evaluation_interval: 5s
  

  external_labels:
    monitor: album-manager

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'album-manager-app'
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app]
        regex: album-manager
        action: keep
