# our base image
FROM ubuntu:latest

RUN apt-get update -y

RUN apt-get install -y python-pip python-dev build-essential

RUN pip install flask prometheus_client

ADD requirements.txt /

RUN pip install -r requirements.txt

# Copying src code to Container
COPY . /data

# Setting Home Directory for containers
WORKDIR /data

# run the application
ENTRYPOINT ["python"]

CMD ["neo_test_album.py"]